### ISSUE TITLE
Token verification error during login

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#327]
# Issue Template

## Description

Token verification error during login because of leftover changes

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to website
2. Click on login
3. See error

## Expected Behavior

Describe what you expected to happen.

## Actual Behavior

Describe what actually happens when you follow the steps.

## Screenshots

![c1](https://github.com/user-attachments/assets/e5b8ae18-8720-455b-94ec-fa365285c757)

```
Token verification error: JsonWebTokenError: invalid signature
    at D:\Projects\GsSoc\notes-app\backend\node_modules\jsonwebtoken\verify.js:171:19
    at getSecret (D:\Projects\GsSoc\notes-app\backend\node_modules\jsonwebtoken\verify.js:97:14)
    at module.exports [as verify] (D:\Projects\GsSoc\notes-app\backend\node_modules\jsonwebtoken\verify.js:101:10)
    at authenticationToken (D:\Projects\GsSoc\notes-app\backend\Routes\Router.js:72:7)
    at Layer.handle [as handle_request] (D:\Projects\GsSoc\notes-app\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Projects\GsSoc\notes-app\backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Projects\GsSoc\notes-app\backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Projects\GsSoc\notes-app\backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Projects\GsSoc\notes-app\backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Projects\GsSoc\notes-app\backend\node_modules\express\lib\router\index.js:346:12)
```
## Additional Context

Add any other context or information about the issue here.

**Comment by mehul-m-prajapati** [comment]
@AyushSharma72 : You can also do this one https://github.com/Scribbie-Notes/notes-app/issues/322.

- I think you have fixed it for mobile. But, for web version, still it does not work

**Comment by mehul-m-prajapati** [comment]
Resolved in https://github.com/Scribbie-Notes/notes-app/pull/353
